### ISSUE TITLE
how to run code?

### ISSUE THREAD

**Issue by kianakiaei** [JohnBoxAnn/TSGL-EEGNet#1]
Hi
I can't run your code. 
Please explain how should run it at README.md
Thank you.

**Comment by JohnBoxAnn** [comment]
Hi,
I'll check and fix it soon. 
@kianakiaei

**Comment by JohnBoxAnn** [comment]
@kianakiaei 
Hi, I’ve upgrade this code. 
Just try to run the script "model_test.py". If nothing goes wrong, it would test the example model on the example data. This means the code is ok. Then, change the parameters and run "train.py" to start a new training~
